global:
   matchSelectors:
     aws_base:
       match_keys:
         provider: aws
       match_labels:
         environment: dev
         purpose: config0
   metadata:   
     labels:
       general: 
         environment: dev
         purpose: config0
     matchSelectors:





custom:
   mongodb-eks:
     stack_name: williaumwu:::mongodb_eks
     arguments: 
       env_name: nosql-eks
       aws_default_region: eu-west-1
       vpc_id: selector:::network_vars::vpc_id
       vpc_name: selector:::network_vars::vpc_name  # selector definition injected by platform configs
       public_subnet_ids: selector:::network_vars::public_subnet_ids:csv  # selector definition injected by platform configs
       private_subnet_ids: selector:::network_vars::private_subnet_ids:csv  # selector definition injected by platform configs
       db_sg_id: selector:::network_vars::db_sg_id  # selector definition injected by platform configs
       eks_cluster_sg_id: selector:::network_vars::bastion_sg_id  # selector definition injected by platform configs
       eks_node_role_arn: selector:::eks_info::node_role_arn  # selector definition injected by platform configs
       mongodb_ami_filter: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
       mongodb_ami_owner: 099720109477 
       mongodb_num_of_replicas: 3
       mongodb_instance_type: t3.micro
       mongodb_disksize: 25
       mongodb_volume_size: 25
       mongodb_username: admin123
       mongodb_password: admin123
       bastion_ami_filter: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*
       bastion_ami_owner: 099720109477 
       bastion_destroy: true 
       bastion_sg_id: selector:::network_vars::bastion_sg_id  # selector definition injected by platform configs
       bastion_subnet_ids: selector:::network_vars::public_subnet_ids  # selector definition injected by platform configs
       cloud_tags_hash:
         environment: dev
         purpose: config0
     spec:
       serialization:
         to_base64:
           arguments:
             - cloud_tags_hash
     metadata:
       labels:
         - general
       matchSelectors:
         - network_vars
         - eks_info
