global:
  arguments: 
    aws_default_region: eu-west-1
  metadata:   
    labels:
      general: 
        environment: dev
        purpose: config0
    matchSelectors:
      network_vars:
        labels:
          environment: dev
          purpose: config0
infrastructure:
  rds:
    stack_name: config0-publish:::aws_rds
    arguments:
      rds_name: config0-rds
      instance_class: db.t3.micro
      engine: MySQL
      allocated_storage: 15
      engine_version: 5.7.44
      vpc_name: selector:::network_vars::vpc_name
      sg_id: selector:::network_vars::db_sg_id
      subnet_ids: selector:::network_vars::private_subnet_ids
      publish_to_saas: true
      cloud_tags_hash:
        environment: dev
        purpose: config0
    spec:
      serialization:
        to_base64:
          arguments:
            - cloud_tags_hash
    metadata:
      labels:
        - general
      matchSelectors:
        - network_vars
