global:
   labels:
     general: 
       environment: dev
       purpose: config0
   matchSelectors:
     aws_base:
       match_keys:
         provider: aws
       match_labels:
         environment: dev
         purpose: config0
   metadata:   
     matchSelectors:
        network_vars:
          labels:
            environment: dev
            purpose: config0
            region: eu-west-1
        vpc_info:
          match_base: aws_base
          match_params:
            must_exists: True
            resource_type: vpc
        public_route_table:
          match_base: aws_base
          match_keys:
            public_route_table: true
          match_params:
            resource_type: route_table
        private_route_table:
          match_base: aws_base
          match_keys:
            private_route_table: true
          match_params:
            resource_type: route_table
        private_subnet_info:
          match_base: aws_base
          match_keys:
            name: private
          match_params:
            resource_type: subnet
        private_subnet_info:
          match_base: aws_base
          match_keys:
            name: private
          match_params:
            resource_type: subnet
        public_subnet_info:
          match_base: aws_base
          match_keys:
            name: public
          match_params:
            resource_type: subnet
        sg_database_info:
          match_base: aws_base
          match_keys:
            name: database
          match_params:
            must_be_one: True
            resource_type: security_group
        sg_bastion_info:
          match_base: aws_base
          match_keys:
            name: bastion
          match_params:
            must_be_one: True
            resource_type: security_group
        sg_web_info:
          match_base: aws_base
          match_keys:
            name: web
          match_params:
            must_be_one: True
            resource_type: security_group
        sg_api_info:
          match_base: aws_base
          match_keys:
            name: api
          match_params:
            must_be_one: True
            resource_type: security_group
custom:
   network:
     stack_name: williaumwu:::aws_vpc_varset_nat_inst
     arguments: 
       vpc_id: selector:::network_vars::vpc_id
       public_subnet_ids: selector:::network_vars::public_subnet_ids
       private_route_table_id: selector:::network_vars::private_route_table_id
       labels_hash:
         region: eu-west-1
         environment: dev
         purpose: config0
         area: network
         cloud: aws
       arguments_hash:
         vpc_name: selector:::vpc_info::name
         vpc_id: selector:::vpc_info::vpc_id
         public_subnet_ids: selector:::public_subnet_info::subnet_id:csv
         private_subnet_ids: selector:::private_subnet_info::subnet_id:csv
         public_route_table_id: selector:::public_route_table::route_table_id
         private_route_table_id: selector:::private_route_table::route_table_id
         db_sg_id: selector:::sg_database_info::sg_id
         bastion_sg_id: selector:::sg_bastion_info::sg_id
         web_sg_id: selector:::sg_web_info::sg_id
         api_sg_id: selector:::sg_api_info::sg_id
         ami_filter: Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*
         ami_owner: 099720109477 
     spec:
       serialization:
         to_base64:
           arguments:
             - labels_hash
             - arguments_hash
     metadata:
       labels:
         - general
       matchSelectors:
         - network_vars
         - vpc_info
         - public_route_table
         - private_route_table
         - public_subnet_info
         - private_subnet_info
         - sg_bastion_info
         - sg_database_info
         - sg_web_info
         - sg_api_info
